//
//  LoginInteractor.swift
//  accessibiliytraining_ios
//
//  Created by Lun Lam on 02/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func setupView(request: Login.SetupView.Request)
    func login( request: Login.Login.Request)
}

protocol LoginDataStore
{}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    
    var presenter: LoginPresentationLogic?
    var worker: LoginWorker?
    
    var listData: ListDataModel?
    
    func setupView(request: Login.SetupView.Request) {
        presenter?.presentSetupView(response: Login.SetupView.Response())
    }
    
    func login(request: Login.Login.Request) {
        if (request.username?.count ?? 0) >= 6 && ( request.username?.count ?? 0 ) <= 16 {            
            self.presenter?.presentLogin(response: Login.Login.Response(success: true))
        }else{
            self.presenter?.presentLogin(response: Login.Login.Response(success: false))
        }
    }
    
}
