//
//  LoginModels.swift
//  accessibiliytraining_ios
//
//  Created by Lun Lam on 02/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases
    
    enum SetupView
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
            let title: String?
            let iconImage: UIImage?
            let usernameTitle: String
            let usernameAccessibilityLabel: String
            let passwordTitle: String
            let passwordAccessibilityLabel: String
            let loginButtonTitle: String
        }
    }
    
    enum Login{
        struct Request {
            let username: String?
            let password: String?
        }
        
        struct Response {
            let success: Bool
        }
        
        struct ViewModel {
            let error: String?
        }
    }
}
