//
//  ListRouter.swift
//  accessibiliytraining_ios
//
//  Created by Lun Lam on 02/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListRoutingLogic
{
    func routeToDetail()
}

protocol ListDataPassing
{
    var dataStore: ListDataStore? { get }
}

class ListRouter: NSObject, ListRoutingLogic, ListDataPassing
{
    weak var viewController: ListViewController?
    var dataStore: ListDataStore?
    
    // MARK: Routing
    func routeToDetail() {
        guard let detail = dataStore?.detail else { return }
        
        let dstVc = DetailConfigurator.createScene(detail: detail)
        viewController?.navigationController?.pushViewController(dstVc, animated: true)
    }

}
