//
//  ListModels.swift
//  accessibiliytraining_ios
//
//  Created by Lun Lam on 02/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum List
{
    struct Row {
        let title: String
        let amount: String
        let date: String
        let arrow: UIImage?
    }
    
    struct Section {
        let headerTitle: String
        let rows: [Row]
    }
    
    enum SetupViews
    {
        struct Request
        {
        }
        struct Response
        {
        }
        struct ViewModel
        {
            let title: String
            let loadingViewTitle: String
            let backButtonAccessibilityLabel: String
        }
    }
    
    enum LoadData {
        struct Request
        {
        }
        struct Response
        {
            let list: ListDataModel
        }
        struct ViewModel
        {
            let sections: [Section]
        }
    }
    
    enum SelectRow {
        struct Request {
            let section: Int
            let row: Int
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
