//
//  ListPresenter.swift
//  accessibiliytraining_ios
//
//  Created by Lun Lam on 02/06/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListPresentationLogic
{
    func presentSetupViews( response: List.SetupViews.Response)
    func presentLoadData( response: List.LoadData.Response )
    func presentSelectRow( response: List.SelectRow.Response )
}

class ListPresenter: ListPresentationLogic
{
    weak var viewController: ListDisplayLogic?

    func presentSetupViews(response: List.SetupViews.Response) {
        viewController?.displaySetUpViews(viewModel: List.SetupViews.ViewModel(
                                            title: "list_page_title".localized,
                                            loadingViewTitle: "common_loading".localized,
                                            backButtonAccessibilityLabel: "common_back".localized))
    }
    
    func presentLoadData(response: List.LoadData.Response) {
        viewController?.displayLoadData(viewModel: List.LoadData.ViewModel(sections: response.list.section.map{
            List.Section(
                headerTitle: $0.headerTitle,
                rows: $0.rows.map{
                    List.Row(
                        title: $0.title,
                        amount: $0.amount,
                        date: $0.date,
                        arrow: $0.detail != nil ? UIImage(named: "ic_forward") : nil )
                })
        }))
    }
    
    func presentSelectRow(response: List.SelectRow.Response) {
        viewController?.displaySelectRow(viewModel: List.SelectRow.ViewModel())
    }
}
